# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }} C++${{ matrix.cpp }} ${{ matrix.build_type }}
    if: github.repository_owner == 'deNBI-cibi' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-19", "clang-18", "clang-17", "gcc-14", "gcc-13", "gcc-12", "intel"]
        cpp: [17, 20, 23, 26]
        build_type: [Release, Debug]
        exclude:
          - compiler: clang-16
            cpp: 26
          - compiler: gcc-13
            cpp: 26
          - compiler: gcc-12
            cpp: 26
          - compiler: gcc-11
            cpp: 26
        include:
          - compiler: gcc-14
            cpp: 17
            cpp_flags: "-Wno-maybe-uninitialized"
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                    -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror ${{ matrix.cpp_flags }}" \
                    -DCMAKE_CXX_STANDARD=${{ matrix.cpp }}

      - name: Build tests
        working-directory: build
        run: make -k

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure

