# SPDX-FileCopyrightText: 2006-2024, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Windows

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: windows-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-${{ matrix.version }}
    timeout-minutes: 180
    if: github.repository_owner == 'deNBI-cibi' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Visual Studio 17 2022"
            version: 2022
            build_type: Release
            cpp: 17

          - name: "Visual Studio 16 2019"
            version: 2019
            build_type: Release
            cpp: 17
    steps:
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure tests
        run: |
          New-Item -Name "build" -ItemType "directory" -Force
          cd build
          cmake .. -G "${{ matrix.name }}" `
                   -DCMAKE_CXX_FLAGS="/EHsc /W4" `
                   -DCMAKE_CXX_STANDARD=${{ matrix.cpp }}

      - name: Build tests
        working-directory: build
        run: cmake --build . --config "${{ matrix.build_type }}" --parallel

      - name: Run tests
        working-directory: build
        run: ctest . -j -C "${{ matrix.build_type }}" --output-on-failure --timeout 240
